### ISSUE TITLE
Simulate de t265 camera

### ISSUE THREAD

**Issue by emanueliwanow** [Auterion/VIO#13]
Hi, I'm trying to use this package in a simulation using the steps that were given in the documentation ( launching the code using the file bridge_mavros_sitl.launch, but apparently the camera that px4 Firmware package simulate is not a T265. This way, the realsense2_camera package does not recognize the camera in the simulation, giving the following warn massage:
```bash
[ WARN] [1599083545.664123240, 18.656000000]: No RealSense devices were found!
```
  Did this launch file ever worked? If so, could you give me the steps to make it work?

**Comment by TSC21** [comment]
https://github.com/Auterion/VIO/issues/9#issuecomment-678315059
