### ISSUE TITLE
ROS2 version ?

### ISSUE THREAD

**Issue by pedro-fuoco** [Auterion/VIO#31]
Hi there! I'd like to know if you plan on expanding this package to ROS2

**Comment by TSC21** [comment]
Not at this point, or at least not planned.

**Comment by pedro-fuoco** [comment]
I've created the ros2 version if anyone else is interested [here it is](https://github.com/SkyRats/realsense_mav_bridge)

**Comment by pedro-fuoco** [comment]
For the time being, it is not possible to use it as mavros_extras odometry plugin is still not available on ros2. But it should work as soon as it is ported

**Comment by pedro-fuoco** [comment]
I've created a [ros2 version](https://github.com/SkyRats/VIO2).
It does not work for now as mavros_extra's odometry plugin is still not available for ros2. I've made a feature request on mavros repository for this issue to be solved.
I will submit it as a pull request when it is ready (waiting for mavros ros2 launch files and odometry plugin)
