### ISSUE TITLE
Ref Frame Conversion and Documentation

### ISSUE THREAD

**Issue by robotastic** [Auterion/VIO#5]
Is there a writeup anywhere on how to configure ROS and PX4 in order to get this to work?

I found this great guide for integrating the T265 with ROS & Ardupilot: https://discuss.ardupilot.org/t/integration-of-ardupilot-and-vio-tracking-camera-part-2-complete-installation-and-indoor-non-gps-flights/43405

One thing they note is that the Reference Frames used by the T265, ROS and the FMU are all different. I looked at the code and didn't see any conversions. Is it assuming the coordinates have already been converted for the FMU?

**Comment by saengphet** [comment]
Hello, Do you have any update? I got the same problem that you mentioned about reference frame transformation from T265 to MAVROS.

**Comment by jkflying** [comment]
The frames should be coming from the launch file. Can you try the lastest master?

**Comment by saengphet** [comment]
> The frames should be coming from the launch file. Can you try the lastest master?

I'll do it soon, thanks a million !!

**Comment by robotastic** [comment]
I ended up using this Python script, which interfaces directly with the t265 camera and spits out MavLink commands. I have tested and it works out of the box with PX4:
https://github.com/thien94/vision_to_mavros/blob/master/scripts/t265_to_mavlink.py

There is a good writeup on the effort here: 
https://discuss.ardupilot.org/t/gsoc-2019-integration-of-ardupilot-and-vio-tracking-camera-for-gps-less-localization-and-navigation/42394

**Comment by jkflying** [comment]
Glad that works for you. For PX4 though, it is recommended to use the ODOMETRY message, with body frame velocity configured in the AID_MASK as described in the PX4 VIO page. This python script will work, but you may have strange interactions if you use it together with GPS.

**Comment by jkflying** [comment]
I've made some PRs to the PX4 user guide / Dev guide, I think together with latest master here this issue can be closed.
