### ISSUE TITLE
T265 data is not utilized by pixhawk ECL 

### ISSUE THREAD

**Issue by echoGee** [Auterion/VIO#7]
The VIO library was run using 

> roslaunch px4_realsense_bridge bridge_mavros.launch gcs_url:="udp://@192.168.6.6:14550" fcu_url:="/dev/ttyS0:921600"

You can see below that the local_position is always zero. 
![2020-05-21_20-03-34_01_GPS, PX4, T265](https://user-images.githubusercontent.com/518314/82620452-7d764200-9ba6-11ea-9178-10bf81c64d7b.png)

The Aid mask was set to 90 
![image](https://user-images.githubusercontent.com/518314/82620930-ba8f0400-9ba7-11ea-8877-645e5610892c.png)

GPS is not used for EKF2, but connected to pixhawk
![2020-05-21_20-03-34_02_GPS](https://user-images.githubusercontent.com/518314/82620456-7f400580-9ba6-11ea-9347-e08ba57f90eb.png)

**Comment by jkflying** [comment]
The configurations which have been tested are listed here:
https://docs.px4.io/master/en/advanced_config/tuning_the_ecl_ekf.html#ekf2_extvis

For without GPS, I would recommend `EV_VEL + ROTATE_EV` if you have magnetometer, otherwise `EV_VEL + EV_YAW` if you don't have magnetometer.

Make sure you are using at least PX4 Firmware 1.10

**Comment by echoGee** [comment]
I did set the mask as 
![image](https://user-images.githubusercontent.com/518314/82684178-2ca32f80-9c20-11ea-88d2-93c2b086c859.png)

I assume you meant to set the "Optical flow" flag for EV_VEL. Not sure how to get EV_YAW. 

Attached are the pixhawk log files and the rosbag of a pattern we moved. The EKF was still not fusing with Optical flow. 

https://drive.google.com/file/d/1-JWr4M8ObpJaRYUfH06vOQ9bS10n_GLw/view?usp=sharing, https://drive.google.com/file/d/1EgOLL4glepxTC1G1ab2LrgyvEpxRxuxs/view?usp=sharing

Notes: 
1. The drone was hand carried in a pattern shown below.
![2020-05-22_11-31-33_01_GPS, PX4, T265](https://user-images.githubusercontent.com/518314/82684521-b81cc080-9c20-11ea-97cc-d777d2a2b926.png)

2. tf frames are here:
[frames.pdf](https://github.com/Auterion/VIO/files/4669046/frames.pdf)

**Comment by jkflying** [comment]
No, you need "Vision Velocity" not "optical flow", which is for dedicated optical flow sensors that need a distance sensor to compensate for distance. You should update your QGC and Firmware to make sure you have these fields.

**Comment by nbelanger99** [comment]
Using 1.10.1 and setting the aid mask as you advised, we can get the camera data to fuse into the pose estimate, however, it's somewhat unreliable and will stop fusing at seemingly random times after the estimation drifts a bit from cam odom. 

We're still confused about how base_link is supposed to relate to the map frame, and still have an unconnected tf tree (please see frames.pdf below). 

Is there any tf that needs to be published that we're missing here?  

https://github.com/Auterion/VIO/files/4669046/frames.pdf

**Comment by echoGee** [comment]
Any suggestions?

**Comment by jkflying** [comment]
For using body-frame velocity I don't think you have an issue, your camera odom is connected to the map. More likely you have vibrations affecting your VIO results, or you need to tune ECL to not reject the VIO solution over the inertial solution.

Try 'flying' the drone by hand without the motors running to see if it is a vibration issue. If the VIO result works well then, you have vibration problems.
